version: "3.8"

services: 
    blog-app:
        image: node:14.17-alpine3.10
        container_name: blog-app
        ports: 
            - "3000:3000"
        stdin_open: true
        tty: true
        volumes: 
            - ./:/app
        working_dir: /app
        depends_on: 
            - mongodb
        #entrypoint: ["yarn", "run", "dev"]

    mongodb:
        image: mongo
        container_name: blog-app-db
        volumes: 
            - blogAppDB:/data/db
    

volumes: 
    blogAppDB: